config/routes.rb
Rails.application.routes.draw do
  root "baits#index"

  resources :baits

  resources :tackle_box_items

  resources :fish_catches do
    resources :likes
  end

  get "activity", to: "activity#index"

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :fish_catch, counter_cache: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_signin
  before_action :find_fish_catch

  def create
    unless already_liked?
      like = @fish_catch.likes.create!(user: current_user)

      respond_to do |format|
        format.html { redirect_to activity_url }
      end
    end
  end

  def destroy
    if already_liked?
      like = current_user.likes.find(params[:id])
      like.destroy!

      respond_to do |format|
        format.html { redirect_to activity_url }
      end
    end
  end

private

  def find_fish_catch
    @fish_catch = FishCatch.find(params[:fish_catch_id])
  end

  def already_liked?
    current_user.likes.exists?(fish_catch_id: @fish_catch.id)
  end
end

app/views/likes/_like_button.html.erb
<div class="like">
  <%= button_to fish_catch_likes_path(fish_catch) do %>
    <%= image_tag("heart-outline.svg") %> <%= fish_catch.likes_count %>
  <% end %>
</div>

app/views/likes/_unlike_button.html.erb
<div class="unlike">
  <%= button_to fish_catch_like_path(fish_catch, like),
        method: :delete do %>
    <%= image_tag("heart.svg") %> <%= fish_catch.likes_count %>
  <% end %>
</div>